Not send availability zones as part of create for edge zones.
kubernetes-sigs/cloud-provider-azure pull request #709
Opened 2021-07-15 16:09 UTC by MirzaSikander

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Cherry pick for #702 : Not send availability zones as part of create for edge zones.

**Release note**:
```
Not send availability zones as part of create for edge zones.
```

2021-07-16 00:17 UTC, andyzhangx reviewed
/ok-to-test

2021-07-16 05:57 UTC, feiskyer requested changes
Could you fix the lint errors?

2021-07-18 10:25 UTC, feiskyer reviewed
/lgtm
/approve

2021-07-18 10:26 UTC, feiskyer approved these changes

2021-07-18 10:26 UTC, merged